/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pushpe
 */
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class MyJFrame extends javax.swing.JFrame {
    
    private final String FILENAME;
    private ArrayList<String> Name =new ArrayList<String>();
    private ArrayList<String> Index =new ArrayList<String>();
    private ArrayList<Double> errorPercentage =new ArrayList<Double>();
    
    private boolean isInputOK = false;
    private double value1 = 0;
    private double value2 = 0;
    private double minError;
    private float thumbFL;
    private float indexFL;
    private float middleFL;
    private float ringFL;
    private float pinkieFL;

    private float thumbFW;
    private float indexFW;
    private float middleFW;
    private float ringFW;
    private float pinkieFW;

    private float thumbFTFD;
    private float indexFTFD;
    private float middleFTFD;
    private float ringFTFD;
    private float pinkieFTFD;

    /**
     * Creates new form NewJFrame
     */
    public MyJFrame() {
        
        URL url = MyJFrame.class.getClassLoader().getResource("data.txt");
        System.out.println(url.getPath());
        this.FILENAME = url.getPath();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ThumbFL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IndexFL = new javax.swing.JTextField();
        MiddleFL = new javax.swing.JTextField();
        RingFL = new javax.swing.JTextField();
        PinkieFL = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ThumbFW = new javax.swing.JTextField();
        IndexFW = new javax.swing.JTextField();
        MiddleFW = new javax.swing.JTextField();
        RingFW = new javax.swing.JTextField();
        PinkieFW = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ThumbFTFD = new javax.swing.JTextField();
        IndexFTFD = new javax.swing.JTextField();
        MiddleFTFD = new javax.swing.JTextField();
        RingFTFD = new javax.swing.JTextField();
        PinkieFTFD = new javax.swing.JTextField();
        AuthenticateButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        minErrorPercentage = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thumb Finger Length");

        ThumbFL.setText("1");
        ThumbFL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThumbFLActionPerformed(evt);
            }
        });

        jLabel2.setText("Index Finger Length");

        jLabel3.setText("Middle Finger Length");

        jLabel4.setText("Ring Finger Length");

        jLabel5.setText("Pinkie Finger Length");

        IndexFL.setText("1");

        MiddleFL.setText("1");

        RingFL.setText("1");

        PinkieFL.setText("1");

        jLabel6.setText("Thumb Finger Width");

        jLabel7.setText("Index Finger Width");

        jLabel8.setText("Middle Finger Width");

        jLabel9.setText("Ring Finger Width");

        jLabel10.setText("Pinkie Finger Width");

        ThumbFW.setText("1");

        IndexFW.setText("1");

        MiddleFW.setText("1");

        RingFW.setText("1");

        PinkieFW.setText("1");

        jLabel11.setText("Thumb Finger Tip to First Division");

        jLabel12.setText("Index Finger Tip to First Division");

        jLabel13.setText("Middle Finger Tip to First Division");

        jLabel14.setText("Ring Finger Tip to First Division");

        jLabel15.setText("Pinkie Finger Tip to First Division");

        ThumbFTFD.setText("1");

        IndexFTFD.setText("1");

        MiddleFTFD.setText("1");

        RingFTFD.setText("1");

        PinkieFTFD.setText("1");

        AuthenticateButton.setText("Authenticate");
        AuthenticateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthenticateButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Error Percentage");

        minErrorPercentage.setText("0.2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IndexFL, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(minErrorPercentage)
                            .addComponent(ThumbFL, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(PinkieFL, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(RingFL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MiddleFL))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ThumbFW)
                                    .addComponent(IndexFW, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(PinkieFW)
                                    .addComponent(RingFW)
                                    .addComponent(MiddleFW))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(RingFTFD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                            .addComponent(MiddleFTFD, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PinkieFTFD)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(8, 8, 8)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ThumbFTFD, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                            .addComponent(IndexFTFD)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(332, 332, 332)
                                .addComponent(AuthenticateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ThumbFL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ThumbFW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(ThumbFTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IndexFL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(IndexFW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(IndexFTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(MiddleFL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(MiddleFW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(MiddleFTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RingFL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(RingFW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(RingFTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(PinkieFL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(PinkieFW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(PinkieFTFD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AuthenticateButton)
                        .addComponent(jLabel16))
                    .addComponent(minErrorPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThumbFLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThumbFLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThumbFLActionPerformed

    private void AuthenticateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthenticateButtonActionPerformed
        int n = 2;
        
        try {
            thumbFL = Float.parseFloat(ThumbFL.getText());
            indexFL = Float.parseFloat(IndexFL.getText());
            middleFL = Float.parseFloat(MiddleFL.getText());
            ringFL = Float.parseFloat(RingFL.getText());
            pinkieFL = Float.parseFloat(PinkieFL.getText());

            thumbFW = Float.parseFloat(ThumbFW.getText());
            indexFW = Float.parseFloat(IndexFW.getText());
            middleFW = Float.parseFloat(MiddleFW.getText());
            ringFW = Float.parseFloat(RingFW.getText());
            pinkieFW = Float.parseFloat(PinkieFW.getText());

            thumbFTFD = Float.parseFloat(ThumbFTFD.getText());
            indexFTFD = Float.parseFloat(IndexFTFD.getText());
            middleFTFD = Float.parseFloat(MiddleFTFD.getText());
            ringFTFD = Float.parseFloat(RingFTFD.getText());
            pinkieFTFD = Float.parseFloat(PinkieFTFD.getText());
            
            minError = Double.parseDouble(minErrorPercentage.getText());
            
            isInputOK = true;
        } catch (Exception e) {
            String message = "All the input fields should be double type";
            JOptionPane.showMessageDialog(null, message);
        } 
        
        if(isInputOK){
        
            value1 = Math.pow(n,0)*thumbFL+Math.pow(n,1)*indexFL+Math.pow(n,2)*middleFL+Math.pow(n,3)*ringFL+Math.pow(n,4)*pinkieFL
                    +Math.pow(n,5)*thumbFW+Math.pow(n,6)*indexFW+Math.pow(n,7)*middleFW+Math.pow(n,8)*ringFW+Math.pow(n,9)*pinkieFW
                    +Math.pow(n,10)*thumbFTFD+Math.pow(n,11)*indexFTFD+Math.pow(n,12)*middleFTFD+Math.pow(n,13)*ringFTFD+Math.pow(n,14)*pinkieFTFD;

            System.out.println("vallue "+ value1);

            BufferedReader br = null;
            FileReader fr = null;

            try {
                fr = new FileReader(FILENAME);
                br = new BufferedReader(fr);

                String sCurrentLine;

                br = new BufferedReader(new FileReader(FILENAME));

                while ((sCurrentLine = br.readLine()) != null) {

                    String[] tempArray = sCurrentLine.split("__");

                    for (int i = 2; i < tempArray.length; i++) {
                        value2 += Math.pow(n, i-2)*Double.parseDouble(tempArray[i]);
                    }
                    System.out.println(value2);

                    errorPercentage.add(Math.abs(((value1-value2)/value2))*100);
                    Name.add(tempArray[1]);
                    Index.add(tempArray[0]);
                    value2 = 0;
                }
                System.out.println("Error Percentages: ");
                for (double i: errorPercentage) {
                    System.out.println("\t"+ i +"%");
                }

                double min = errorPercentage.get(0);

                for(double i: errorPercentage) {
                    if(i < min) min = i;
                }
                System.out.println("Minimum Error Percentage:");
                System.out.println("\t"+ min +"%");


                for (int i = 0; i < errorPercentage.size(); i++) {

                    if(errorPercentage.get(i) == min){
                        if(min <= minError){

                            String message = "Best match is found \n\t Name:" + Name.get(i) + " Index: "+ Index.get(i);
                            System.out.println(message);
                            JOptionPane.showMessageDialog(null, message);

                        }else{

                            String message = "You are not authenticated. Error Percentage is higher than "+minError+"%";
                            System.out.println(message);
                            JOptionPane.showMessageDialog(null, message);
                        }
                    }
                }
                errorPercentage.clear();
                Name.clear();
                Index.clear();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                try {
                    if (br != null)
                            br.close();

                    if (fr != null)
                            fr.close();

                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
        
        isInputOK = false;
    }//GEN-LAST:event_AuthenticateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AuthenticateButton;
    private javax.swing.JTextField IndexFL;
    private javax.swing.JTextField IndexFTFD;
    private javax.swing.JTextField IndexFW;
    private javax.swing.JTextField MiddleFL;
    private javax.swing.JTextField MiddleFTFD;
    private javax.swing.JTextField MiddleFW;
    private javax.swing.JTextField PinkieFL;
    private javax.swing.JTextField PinkieFTFD;
    private javax.swing.JTextField PinkieFW;
    private javax.swing.JTextField RingFL;
    private javax.swing.JTextField RingFTFD;
    private javax.swing.JTextField RingFW;
    private javax.swing.JTextField ThumbFL;
    private javax.swing.JTextField ThumbFTFD;
    private javax.swing.JTextField ThumbFW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField minErrorPercentage;
    // End of variables declaration//GEN-END:variables
}
